### ISSUE TITLE
Decode Algorithm Source

### ISSUE THREAD

**Issue by azizarc88** [nsNeruno/qris#1]
Hello, just wondering
the decode process that you made in this package is coming from official documentation (Bank Indonesia) or not yah ?

**Comment by nsNeruno** [comment]
Rather than Bank Indonesia,
It's from ASPI's Classified Document shared internally.

Document not published for obvious legal reason.

**Comment by azizarc88** [comment]
so you work there, at ASPI ?, 'cause you can have the documents 🤔

**Comment by nsNeruno** [comment]
No, under a cooperation contract with ASPI
